# Configurações do servidor
server.port=8080

# Configurações do Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Configurações da aplicação Googol
googol.rmi.host=localhost
googol.rmi.port=1099
googol.rmi.websocket.port=1097